version: 0.2  


phases:
  pre_build:
    commands:
    - npm install
  build:
      commands:
        - echo Build started on `date`
artifacts:
  files:
    - C:/Users/erata/OneDrive/Desktop/Excersice/NodeJs-App.zip
 discard-paths: yes
 
